### PR TITLE
Fix Proxy response caching

### LINKED ISSUE #207: HTTP Caching - metadata endpoint
I've tried a Laravel project (with a few internal packages) going through a self-hosted install, then the hosted version.

Both repman installs are taking around 30 minutes to run with composer v1. This compares to 25 seconds when using packagist directly.

I believe the reason for this is that there are no cache headers on any of the repman responses.

```
> curl -I https://packagist.org/p/illuminate/console.json   
HTTP/2 200 
server: nginx
date: Mon, 29 Jun 2020 12:02:11 GMT
content-type: application/json
content-length: 23256452
last-modified: Mon, 29 Jun 2020 05:11:16 GMT
vary: Accept-Encoding
etag: "5ef977f4-162dd84"
access-control-allow-origin: *
access-control-allow-methods: GET
access-control-allow-headers: X-Requested-With,If-Modified-Since
accept-ranges: bytes
```

```
> curl -I https://repo.repman.io/p/illuminate/console
HTTP/2 200 
content-type: application/json
content-length: 0
server: nginx
cache-control: no-cache, private
date: Mon, 29 Jun 2020 12:03:07 GMT
x-cache: Hit from cloudfront
via: 1.1 b4d3f424b1e6960b9f71e8cf3b9e1a57.cloudfront.net (CloudFront)
x-amz-cf-pop: ICN51-C1
x-amz-cf-id: XfTtcCR__cGq15VB5rnQGIH7SeG1v7sx_YKjrr28pNzCqcG6rAAOJA==
age: 6
```

```
> curl -I https://repo.repman.myinternaldomain.local/p/illuminate/routing
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 29 Jun 2020 12:04:45 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/7.4.5
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
```

This one file itself is 25MB, and my Laravel install ends up downloading 500MB every time I try a composer update.

### PR DESCRIPTION
**Pull request by giggsey**
Only add the Response stream if the Request results in a cache miss.

Fixes #207

### CODE REVIEW

**Comment by giggsey** [comment]
I think the `distribution` function in ProxyController can also do the same thing here

**Comment by giggsey** [comment]
Before:

```
curl -w "@.curl-format.txt" 'http://127.0.0.1:8000/p/symfony/http-foundation' -H 'If-Modified-Since: Tue, 18 Aug 2020 18:37:05 GMT' -H 'Host: repo.repman.wip' -v
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET /p/symfony/http-foundation HTTP/1.1
> Host: repo.repman.wip
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
> Accept: */*
> Referer: 
> If-Modified-Since: Tue, 18 Aug 2020 18:37:05 GMT
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Cache-Control: public
< Content-Length: 2374308
< Content-Type: application/json
< Date: Tue, 18 Aug 2020 19:06:20 GMT
< Date: Tue, 18 Aug 2020 19:06:20 GMT
< Host: repo.repman.wip
< Last-Modified: Tue, 18 Aug 2020 18:37:05 GMT
< 
{"packages":{"notadd/wechat":{"dev-master":{"name":"notadd/wechat","description":"Notadd's Wechat Module.","keywords":["framework","cms","member","notadd"],"homepage":"https://notadd.com","version":"dev-m
...
time_namelookup:  0.000021s
       time_connect:  0.000121s
    time_appconnect:  0.000000s
   time_pretransfer:  0.000210s
      time_redirect:  0.000000s
 time_starttransfer:  0.351384s
                    ----------
         time_total:  0.872798s
```

After:

```
curl -w "@.curl-format.txt" 'http://127.0.0.1:8000/p/symfony/http-foundation' -H 'If-Modified-Since: Tue, 18 Aug 2020 18:37:05 GMT' -H 'Host: repo.repman.wip' -v
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET /p/symfony/http-foundation HTTP/1.1
> Host: repo.repman.wip
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
> Accept: */*
> Referer: 
> If-Modified-Since: Tue, 18 Aug 2020 18:37:05 GMT
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 304 Not Modified
< Accept-Ranges: bytes
< Cache-Control: public
< Date: Tue, 18 Aug 2020 19:07:38 GMT
< Date: Tue, 18 Aug 2020 19:07:38 GMT
< Host: repo.repman.wip
< 
* Connection #0 to host 127.0.0.1 left intact
    time_namelookup:  0.000024s
       time_connect:  0.000246s
    time_appconnect:  0.000000s
   time_pretransfer:  0.000960s
      time_redirect:  0.000000s
 time_starttransfer:  0.331560s
                    ----------
         time_total:  0.331640s

```

**Comment by akondas** [comment]
Nice, looks promising, I need to verify it, but we'll probably merge it. Thanks :beers:

File: src/Controller/ProxyController.php [hunk 1]
```diff
@@ -78,6 +78,14 @@ public function legacyMetadata(string $package): Response
             ->setPublic()
             ->setLastModified((new \DateTime())->setTimestamp($metadata->timestamp()))
         ;
+
+        if ($response->isNotModified($request)) {
+            return $response;
+        }
```
Comment (akondas) [inline src/Controller/ProxyController.php:84]: I think we can get rid of this statement since:
```php
    /**
     * Determines if the Response validators (ETag, Last-Modified) match
     * a conditional value specified in the Request.
     *
     * If the Response is not modified, it sets the status code to 304 and
     * removes the actual content by calling the setNotModified() method.
     *
     * @return bool true if the Response validators match the Request, false otherwise
     *
     * @final
     */
    public function isNotModified(Request $request): bool
```

So maybe something like this:
```php
        $response = (new StreamedResponse(ResponseCallback::fromStream($metadata->stream()), 200, [
            'Accept-Ranges' => 'bytes',
            'Content-Type' => 'application/json',
            /* @phpstan-ignore-next-line */
            'Content-Length' => fstat($metadata->stream())['size'],
        ]))
            ->setPublic()
            ->setLastModified((new \DateTime())->setTimestamp($metadata->timestamp()))
        ;
        $response->isNotModified($request);

        return $response;
```

Comment (akondas) [reply src/Controller/ProxyController.php:84]: And please add this also to distribution method, thanks :wink:

Comment (giggsey) [reply src/Controller/ProxyController.php]: Added to distribution & the overall package list (the four places in the project that the cache is public)

**Review by akondas — APPROVED** [review]

**Comment by akondas** [comment]
Thanks @giggsey :beers:
